# Generated by Django 3.0.1 on 2019-12-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
