# Generated by Django 3.0.1 on 2019-12-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0002_contactinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
