# Generated by Django 3.0.1 on 2019-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0003_auto_20191220_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
